### ISSUE TITLE
Dark mode and Light mode

### ISSUE THREAD

**Issue by dinhanhx** [dinhanhx/text-summarizer#12]
Like the title, now we have well implemented frontend. 
We should focus on making dark mode and light mode.
@huonglarne 
@DDHLong 

Deadline: Sunday 19/04/2020

**Comment by dinhanhx** [comment]
Make the darkmode and lightmode!!!

**Comment by dinhanhx** [comment]
From TAH [suggestion](https://docs.google.com/spreadsheets/d/1e_CMn7jPzwN--3maW5AOUZD-UXiGPR8Y_EuQPcQvYok/edit?disco=AAAAJakGW3c), use [Boostrap](https://getbootstrap.com/)

**Comment by dinhanhx** [comment]
## Note
Remember to create a branch "dark-light-mode" then create a pull request (also linked to relevant project, issues)

**Comment by huonglarne** [comment]
@DDHLong hey I dont know what to do since I've never done this before so just tell me my job and I will get it done

**Comment by dinhanhx** [comment]
Must read this [Templates](https://www.tutorialspoint.com/flask/flask_templates.htm) and [Static](https://www.tutorialspoint.com/flask/flask_static_files.htm)
