### ISSUE TITLE
Automated black box testing

### ISSUE THREAD

**Issue by dinhanhx** [dinhanhx/text-summarizer#13]
(Rewrite)
I assume you can run the web app and install everything.
# Manually testing
## Raw text (First input in the page)
Just prepare around 100 - 200 English words
## Wikipedia 
Just prepare around 5 to 10 English articles to test each time
## Document
Just prepare around 2 sample for each .docx, .pdf, .odt
## Dark/light mode button
Just click several times

# Automatically testing

I will assume you know Python, packaging, modules and testing.

[What to test backend](https://github.com/dinhanhx/text-summarizer/wiki#4-library-abberivator_flow)

[Should read Python Testing](https://realpython.com/python-testing/) and [Coverage report](https://coverage.readthedocs.io/en/coverage-5.1/)

What to test frontend: Dark/light mode button and 3 main input buttons

[Should read Cypress](https://www.cypress.io/)

**Comment by huonglarne** [comment]
can i do this? although i would need some help too.

**Comment by dinhanhx** [comment]
I assign you already. feel free to do.

**Comment by huonglarne** [comment]
hey Dinh Anh, Cypress's default work space is a separate folder named cypress in the root so i cannot put the test files in test/cypress

**Comment by dinhanhx** [comment]
Can we just copy and paste test code (.js) and test result (.txt) to 'test/cypress' folder?

**Comment by huonglarne** [comment]
I added a branch for my cypress testing. Try downloading it and test, but only the files i edited because i didnt pull before commiting new changes.

**Comment by dinhanhx** [comment]
@huonglarne can you tell @DDHLong to do this? I  am busy and I think I have no time to learn how use cypress. I will just check for conflict between branches.
