### ISSUE TITLE
Need more sample links

### ISSUE THREAD

**Issue by dinhanhx** [dinhanhx/text-summarizer#27]
Like the title, due to the fact that text-summarizer can only take English Wikipedia articles, we need more links like this 
```
https://en.wikipedia.org/wiki/Main_Page
``` 
The submitted file should be `links.txt`. Each line is a link.  In ['case' folder](https://github.com/dinhanhx/text-summarizer/tree/master/test/case)

**Comment by huonglarne** [comment]
sure, i will do it today

**Comment by dinhanhx** [comment]
@huonglarne If so, I will assign you too.

**Comment by dinhanhx** [comment]
@huonglarne when you write commit msg, make sure you have Issue #number in.
For example `git commit -m "Add 34567 links in links.txt Issue #27"` `#27` is the Id of this issue.

**Comment by dinhanhx** [comment]
Solved by 
62f479c
