### ISSUE TITLE
Summarization for .odt and .doc/.docx files 

### ISSUE THREAD

**Issue by dinhanhx** [dinhanhx/text-summarizer#4]
Nguyen Nhu Hieu works on this!

**Comment by dinhanhx** [comment]
# odt file parser
[odt file](https://pypi.org/project/odfpy/)
# doc file parser
[doc file](https://stackoverflow.com/questions/36001482/read-doc-file-with-python)

**Comment by dinhanhx** [comment]
# Where ot learn Python?
[Here](https://www.tutorialspoint.com/python/index.htm)

**Comment by dinhanhx** [comment]
@hieunguyen7337 if you can't do this, I am afraid that I have to mark you as disqualified for this project.

**Comment by hieunguyen7337** [comment]
Since your file already exist I figure that I would try to applied it and one way I can think of is to convert Doc file to PDF 
[DOCtoPDFConverter.zip](https://github.com/dinhanhx/text-summarizer/files/4396805/DOCtoPDFConverter.zip)

**Comment by hieunguyen7337** [comment]
I'm trying to change input output of the program and somehow can't find a way to upload python file

**Comment by hieunguyen7337** [comment]
for ODT converter
[ODTtoPDFConverter.zip](https://github.com/dinhanhx/text-summarizer/files/4396815/ODTtoPDFConverter.zip)

**Comment by dinhanhx** [comment]
@hieunguyen7337 It's okay man, call me whenever you want in today

**Comment by hieunguyen7337** [comment]
upload doc_abberivator, haven't debug because still can't make ubuntu install the request module
(pretty sure it is request not requests)

**Comment by hieunguyen7337** [comment]
Add module, not sure if it can be install correctly, need testing

**Comment by dinhanhx** [comment]
Maybe it only works pip3 cmd, I guess? @hieunguyen7337

**Comment by dinhanhx** [comment]
@hieunguyen7337 One more things, it's 'urllib.request' module not 'request' module

**Comment by dinhanhx** [comment]
@hieunguyen7337 Try this [link](https://stackoverflow.com/questions/47730259/installing-urllib-in-python3-6)
Did you try cmd 'python3' and 'pip3'?

**Comment by hieunguyen7337** [comment]
I seriously doubt it would be this simple

**Comment by hieunguyen7337** [comment]
but here's the code

**Comment by hieunguyen7337** [comment]
have not function yet

**Comment by dinhanhx** [comment]
You are supposed to embed your link within your comment. We will talk about this later.

**Comment by dinhanhx** [comment]
[How to get file extension](https://www.tutorialspoint.com/How-to-extract-file-extension-using-Python)

**Comment by dinhanhx** [comment]
To be honest @hieunguyen7337, you should learn from Huong. I told her the same protocol  of 'How to implement new functions, modules, scripts'. She followed it correctly.  Base on her codes and try to follow the protocol, finish the this task. If you don't understand or mess up, ask @huonglarne and me.
